config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :finances
  resources :events
  resources :users
  resources :communities do
    collection do
      get :set_community_session
      get :events
      get :members
    end
  end
  resources :roles1
  get "home/index"
  root "home#index"
  get "registrations/new"
  resource :session
  resource :registration, only: %i[new create]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/payment.rb
class Payment < ApplicationRecord
  # Validations
  validates :amount, presence: true
  validates :payment_method, presence: true
  validates :notes, presence: true
  validates :status, presence: true
  validates :paid_at, presence: true

  ## update the ransackable below with column you want to add ransack
  def self.ransackable_attributes(auth_object = nil)
    ["id"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments
  def index
    @q = Payment.ransack(params[:q])
    @pagy, @payments = pagy(@q.result(distinct: true).order(created_at: :desc))
    @payment_form = Payment.new
  end

  # GET /payments/1
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  def create
    @payment = Payment.new(payment_params)

    if @payment.save
      redirect_to payments_path, notice: "Payment was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /payments/1
  def update
    if @payment.update(payment_params)
      redirect_to payments_path, notice: "Payment was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /payments/1
  def destroy
    @payment.destroy!
    redirect_to payments_path, notice: "Payment was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.expect(payment: [ :amount, :payment_method, :notes, :status, :paid_at ])
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, class: "contents text-white flex flex-col gap-5 mt-4" ) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :amount, placeholder: "amount", class: ["block shadow-sm rounded-md border bg-gray-700 px-3 py-2 mt-2 w-full", {"border-gray-600 focus:outline-blue-600": payment.errors[:amount].none?, "border-red-400 focus:outline-red-600": payment.errors[:amount].any?}] %>
  </div>

  <div>
    <%= form.number_field :payment_method, placeholder: "payment_method", class: ["block shadow-sm rounded-md border bg-gray-700 px-3 py-2 mt-2 w-full", {"border-gray-600 focus:outline-blue-600": payment.errors[:payment_method].none?, "border-red-400 focus:outline-red-600": payment.errors[:payment_method].any?}] %>
  </div>

  <div>
    <%= form.text_field :notes, placeholder: "notes", class: ["block shadow-sm rounded-md border bg-gray-700 px-3 py-2 mt-2 w-full", {"border-gray-600 focus:outline-blue-600": payment.errors[:notes].none?, "border-red-400 focus:outline-red-600": payment.errors[:notes].any?}] %>
  </div>

  <div>
    <%= form.number_field :status, placeholder: "status", class: ["block shadow-sm rounded-md border bg-gray-700 px-3 py-2 mt-2 w-full", {"border-gray-600 focus:outline-blue-600": payment.errors[:status].none?, "border-red-400 focus:outline-red-600": payment.errors[:status].any?}] %>
  </div>

  <div>
    <%= form.datetime_field :paid_at, placeholder: "paid_at", class: ["block shadow-sm rounded-md border bg-gray-700 px-3 py-2 mt-2 w-full", {"border-gray-600 focus:outline-blue-600": payment.errors[:paid_at].none?, "border-red-400 focus:outline-red-600": payment.errors[:paid_at].any?}] %>
  </div>

  <div>
    <%= form.submit nil, class:"font-bold px-4 py-2 bg-blue-600 text-white rounded-md shadow-md hover:bg-blue-500 inline-flex items-center" %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
      <td class="p-4 text-base font-medium text-gray-900 whitespace-nowrap dark:text-white">
      <%= payment.amount %>
    </td>
        <td class="p-4 text-base font-medium text-gray-900 whitespace-nowrap dark:text-white">
      <%= payment.payment_method %>
    </td>
        <td class="p-4 text-base font-medium text-gray-900 whitespace-nowrap dark:text-white">
      <%= payment.notes %>
    </td>
        <td class="p-4 text-base font-medium text-gray-900 whitespace-nowrap dark:text-white">
      <%= payment.status %>
    </td>
        <td class="p-4 text-base font-medium text-gray-900 whitespace-nowrap dark:text-white">
      <%= payment.paid_at %>
    </td>
  </div>

app/views/payments/edit.html.erb
<% content_for :title, "Editing payment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing payment</h1>

  <%= render "form", payment: @payment %>

  <%= link_to "Show this payment", @payment, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to payments", payments_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/payments/new.html.erb
<% content_for :title, "New payment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New payment</h1>

  <%= render "form", payment: @payment %>

  <%= link_to "Back to payments", payments_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/payments/show.html.erb
<% content_for :title, "Showing payment" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing payment</h1>

  <%= render @payment %>

  <%= link_to "Edit this payment", edit_payment_path(@payment), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to payments", payments_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this payment", @payment, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>