config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :finances
  resources :events
  resources :users
  resources :communities do
    collection do
      get :set_community_session
      get :events
      get :members
    end
  end
  resources :roles1
  get "home/index"
  root "home#index"
  get "registrations/new"
  resource :session
  resource :registration, only: %i[new create]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :community_members
  has_many :event_communities
  has_one :finance
  has_many :events, through: :event_communities
  has_many :members, through: :community_members, source: :user
  # Validations
  validates :name, presence: true
  validates :descriptions, presence: true

  scope :my_community, -> { where(id: CommunityMember.where(user_id: Current.user.id).select(:community_id)) }

  %i[members events].each do |association|
    define_method("total_#{association}") do
      count = send(association).count
      count >= 10 ? "#{(count / 10) * 10}+" : count.to_s
    end
  end

  def top_three
    members.first(3)
  end

  ## update the ransackable below with column you want to add ransack
  def self.ransackable_attributes(auth_object = nil)
    [ "id" ]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: %i[ show edit update destroy ]

  # GET /communities
  def index
    @q = Current.user.admin? ? Community.ransack(params[:q]) : Community.my_community.ransack(params[:q])
    @pagy, @communities = pagy(@q.result(distinct: true).order(created_at: :desc))
    @community_form = Community.new
  end

  # GET /communities/1
  def show
    @q = @community.events.ransack(params[:q])
    @pagy_all, @all_events = pagy(@q.result(distinct: true).order(created_at: :desc), limit: 5)
    @pagy_upcoming, @upcoming_events = pagy(@q.result(distinct: true).where(status: "upcoming").order(created_at: :desc), limit: 5)
    @pagy_ongoing, @ongoing_events = pagy(@q.result(distinct: true).where(status: "ongoing").order(created_at: :desc), limit: 5)
    @pagy_completed, @completed_events = pagy(@q.result(distinct: true).where(status: "completed").order(created_at: :desc), limit: 5)
    @pagy_members, @members = pagy(@community.members.ransack(params[:q]).result(distinct: true).order(created_at: :desc), limit: 5)
  end

  def set_community_session
    session[:community] = Community.find(params[:community_id])
    redirect_to root_path, notice: "Community was successfully set."
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  def create
    @community = Community.new(community_params)

    if @community.save
      redirect_to communities_path, notice: "Community was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /communities/1
  def update
    if @community.update(community_params)
      redirect_to communities_path, notice: "Community was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /communities/1
  def destroy
    @community.destroy!
    redirect_to communities_path, notice: "Community was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def community_params
      params.expect(community: [ :name, :descriptions ])
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_community.html.erb
<div id=<%= dom_id(community) %>>
  <td class="p-4 text-base font-medium text-gray-900 whitespace-nowrap dark:text-white">
    <%= community.name %>
  </td>
  <td class="p-4 text-base font-medium text-gray-900 whitespace-nowrap dark:text-gray-500">
    <%= community.descriptions.truncate(80) %>
  </td>
  <td class="p-4 text-base font-medium text-gray-900 whitespace-nowrap dark:text-gray-500">
    <div class="flex -space-x-4 rtl:space-x-reverse items-center">
      <% community.top_three.each do |member| %>
        <img src="https://randomuser.me/api/portraits/thumb/men/<%= member.id.to_i % 100 %>.jpg" alt="<%= member.username %>" class="w-10 h-10 border-2 border-white rounded-full dark:border-gray-800">
      <% end %>
      <span class="ml-5"><%= community.total_members %></span>
    </div>
  </td>
</div>

app/views/communities/_form.html.erb
<%= form_with(model: community, class: "contents text-white flex flex-col gap-5 mt-4" ) do |form| %>
  <% if community.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
        <% community.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "name", class: ["block shadow-sm rounded-md border bg-gray-700 px-3 py-2 mt-2 w-full", {"border-gray-600 focus:outline-blue-600": community.errors[:name].none?, "border-red-400 focus:outline-red-600": community.errors[:name].any?}] %>
  </div>

  <div>
    <%= form.textarea :descriptions, placeholder: "descriptions", class: ["block shadow-sm rounded-md border bg-gray-700 px-3 py-2 mt-2 w-full", {"border-gray-600 focus:outline-blue-600": community.errors[:descriptions].none?, "border-red-400 focus:outline-red-600": community.errors[:descriptions].any?}] %>
  </div>

  <div>
    <%= form.submit nil, class:"font-bold px-4 py-2 bg-blue-600 text-white rounded-md shadow-md hover:bg-blue-500 inline-flex items-center" %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<% content_for :title, "Editing community" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing community</h1>

  <%= render "form", community: @community %>

  <%= link_to "Show this community", @community, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to communities", communities_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/communities/new.html.erb
<% content_for :title, "New community" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New community</h1>

  <%= render "form", community: @community %>

  <%= link_to "Back to communities", communities_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/communities/show.html.erb
<% content_for :title, "Showing community" %>
<div class="w-full">
  <div class="p-4 bg-white block sm:flex items-center justify-between border-b border-gray-200 lg:mt-1.5 dark:bg-gray-800 dark:border-gray-700">
    <div class="w-full mb-1">
      <div class="mb-4">
        <nav class="flex mb-5" aria-label="Breadcrumb">
          <ol class="inline-flex items-center space-x-1 text-sm font-medium md:space-x-2">
            <li class="inline-flex items-center">
              <a href="/" class="inline-flex items-center text-gray-700 hover:text-blue-600 dark:text-gray-300 dark:hover:text-white">
                <svg class="w-5 h-5 mr-2.5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"></path></svg>
                Home
              </a>
            </li>
            <div class="flex items-center">
              <a href="/communities" class="inline-flex items-center text-gray-700 hover:text-blue-600 dark:text-gray-300 dark:hover:text-white">
                <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                Communities
              </a>
            </div>
            <div class="flex items-center">
              <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
              <span class="ml-1 text-gray-400 md:ml-2 dark:text-gray-500" aria-current="page"><%= @community.name %></span>
            </div>
          </li>
        </ol>
      </nav>
      <div class="text-5xl flex items-center font-semibold text-gray-900 dark:text-white ">
        <div class="flex flex-col items-start">
          <div><%= @community.name %></div>
          <div class="text-sm font-normal text-gray-500 dark:text-gray-400"> <%= @community.descriptions %></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="w-full">
  <section class="relative overflow-x-hidden bg-white dark:bg-gray-800 px-70">
    <div class="w-full flex flex-col items-center justify-center">
      <div class="border-b border-gray-200 dark:border-gray-700 py-2 w-full text-center text-2xl font-bold">Event</div>
      <!-- Search Bar -->
      <!-- Tabs -->
      <div class="border-b w-full flex justify-center border-gray-200 dark:border-gray-700">
        <ul class="flex flex-wrap -mb-px text-sm font-medium text-center" id="default-styled-tab" data-tabs-toggle="#default-styled-tab-content" data-tabs-active-classes="text-purple-600 hover:text-purple-600 dark:text-purple-500 dark:hover:text-purple-500 border-purple-600 dark:border-purple-500" data-tabs-inactive-classes="dark:border-transparent text-gray-500 hover:text-gray-600 dark:text-gray-400 border-gray-100 hover:border-gray-300 dark:border-gray-700 dark:hover:text-gray-300" role="tablist">
          <li role="presentation">
            <button class="inline-block p-4 border-b-2 rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" id="all-styled-tab" data-tabs-target="#styled-all" type="button" role="tab" aria-controls="all" aria-selected="false">All</button>
          </li>
          <li class="me-2" role="presentation">
            <button class="inline-block p-4 border-b-2 rounded-t-lg" id="upcoming-styled-tab" data-tabs-target="#styled-upcoming" type="button" role="tab" aria-controls="upcoming" aria-selected="false">Upcoming</button>
          </li>
          <li class="me-2" role="presentation">
            <button class="inline-block p-4 border-b-2 rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" id="dashboard-styled-tab" data-tabs-target="#styled-dashboard" type="button" role="tab" aria-controls="dashboard" aria-selected="false">on Going</button>
          </li>
          <li class="me-2" role="presentation">
            <button class="inline-block p-4 border-b-2 rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" id="completed-styled-tab" data-tabs-target="#styled-completed" type="button" role="tab" aria-controls="completed" aria-selected="false">Completed</button>
          </li>
        </ul>
      </div>
      <div id="default-styled-tab-content" class="w-full">
        <div class="hidden p-4 rounded-lg bg-gray-50 dark:bg-gray-800" id="styled-upcoming" role="tabpanel" aria-labelledby="upcoming-tab">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <th scope="col" class="px-6 py-3">Event Name</th>
                <th scope="col" class="px-6 py-3">Date</th>
              </tr>
            </thead>
            <tbody>
              <% @upcoming_events.each do |event| %>
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                  <td class="px-6 py-4"><%= link_to event.name, event %></td>
                  <td class="px-6 py-4"><%= event.date %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="hidden p-4 rounded-lg bg-gray-50 dark:bg-gray-800" id="styled-dashboard" role="tabpanel" aria-labelledby="dashboard-tab">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <th scope="col" class="px-6 py-3">Event Name</th>
                <th scope="col" class="px-6 py-3">Date</th>
              </tr>
            </thead>
            <tbody>
              <% @ongoing_events.each do |event| %>
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                  <td class="px-6 py-4"><%= link_to event.name, event %></td>
                  <td class="px-6 py-4"><%= event.date %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="hidden p-4 rounded-lg bg-gray-50 dark:bg-gray-800" id="styled-completed" role="tabpanel" aria-labelledby="completed-tab">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <th scope="col" class="px-6 py-3">Event Name</th>
                <th scope="col" class="px-6 py-3">Date</th>
              </tr>
            </thead>
            <tbody>
              <% @completed_events.each do |event| %>
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                  <td class="px-6 py-4"><%= link_to event.name, event %></td>
                  <td class="px-6 py-4"><%= event.date %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="hidden p-4 rounded-lg bg-gray-50 dark:bg-gray-800" id="styled-all" role="tabpanel" aria-labelledby="all-tab">
          <%= search_form_for @q, url: community_path(@community), method: :get, class: "mb-4" do |f| %>
            <div class="flex items-center space-x-4 w-full">
              <div class="w-full">
                <%= f.search_field :name_cont, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500", placeholder: "Name" %>
              </div>
              <div class="flex items-end">
                <%= f.submit "Search", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
              </div>
            </div>
          <% end %>
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <th scope="col" class="px-6 py-3">Event Name</th>
                <th scope="col" class="px-6 py-3">Date</th>
                <th scope="col" class="px-6 py-3">status</th>
              </tr>
            </thead>
            <tbody>
              <% @all_events.each do |event| %>
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                  <td class="px-6 py-4"><%= link_to event.name, event %></td>
                  <td class="px-6 py-4"><%= event.date %></td>
                  <td class="px-6 py-4"><%= event.status %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="w-full border-b border-r border-l border-gray-200 dark:border-gray-700 w-full text-center">
            <%= render 'shared/pagination', pagy: @pagy_all %>
          </div>
        </div>
      </div>
      <div class="border-b border-t border-gray-200 dark:border-gray-700 py-2 w-full text-center text-2xl font-bold mb-10">Member</div>
      <div class="flex flex-wrap gap-2 w-full">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-6 py-3">Username</th>
            </tr>
          </thead>
          <tbody>
            <% @members.each do |member| %>
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <td class="px-6 py-4">
                  <img src="https://randomuser.me/api/portraits/thumb/men/<%= member.id.to_i % 100 %>.jpg" alt="<%= member.username %>" class="w-8 h-8 rounded-full mr-2 inline-block">
                  <%= link_to member.username, member %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= render 'shared/pagination', pagy: @pagy_members %>
      </div>
    </section>
  </div>
</div>