config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :finances
  resources :events
  resources :users
  resources :communities do
    collection do
      get :set_community_session
      get :events
      get :members
    end
  end
  resources :roles1
  get "home/index"
  root "home#index"
  get "registrations/new"
  resource :session
  resource :registration, only: %i[new create]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :community_members
  has_many :event_communities
  has_one :finance
  has_many :events, through: :event_communities
  has_many :members, through: :community_members, source: :user
  # Validations
  validates :name, presence: true
  validates :descriptions, presence: true

  scope :my_community, -> { where(id: CommunityMember.where(user_id: Current.user.id).select(:community_id)) }

  %i[members events].each do |association|
    define_method("total_#{association}") do
      count = send(association).count
      count >= 10 ? "#{(count / 10) * 10}+" : count.to_s
    end
  end

  def top_three
    members.first(3)
  end

  ## update the ransackable below with column you want to add ransack
  def self.ransackable_attributes(auth_object = nil)
    [ "id" ]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/community_member.rb
class CommunityMember < ApplicationRecord
  belongs_to :community
  belongs_to :user
  # Validations

  ## update the ransackable below with column you want to add ransack
  def self.ransackable_attributes(auth_object = nil)
    ["id"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_communities
  has_one :event_detail
  has_many :event_schedules
  has_many :communities, through: :event_communities
  has_many :event_users, through: :event_communities, source: :user
  belongs_to :community
  # Validations
  validates :name, presence: true
  validates :date, presence: true

  enum :status, %i[upcoming ongoing completed], default: :upcoming

  def event_communities_by_role(role)
    event_communities.where(role: role)
  end

  ## update the ransackable below with column you want to add ransack
  def self.ransackable_attributes(auth_object = nil)
    [ "id", "name" ]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/event_community.rb
class EventCommunity < ApplicationRecord
  belongs_to :user
  belongs_to :community
  belongs_to :event
  # Validations
  validates :role, presence: true
  validates :title, presence: true

  enum :role, {
    collaborator: 0,
    organizer: 1,
    attendant: 2
  }
  ## update the ransackable below with column you want to add ransack
  # def self.ransackable_attributes(auth_object = nil)
  #   ["id"]
  # end

  # def self.ransackable_associations(auth_object = nil)
  #   []
  # end
end

app/models/event_detail.rb
class EventDetail < ApplicationRecord
  belongs_to :event
  # Validations
  validates :date, presence: true
  validates :start, presence: true
  validates :finish, presence: true
  validates :price, presence: true
  validates :descriptions, presence: true

  ## update the ransackable below with column you want to add ransack
  def self.ransackable_attributes(auth_object = nil)
    ["id"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/event_schedule.rb
class EventSchedule < ApplicationRecord
  belongs_to :event
  belongs_to :user
  # Validations
  validates :title, presence: true
  validates :start, presence: true
  validates :finish, presence: true

  ## update the ransackable below with column you want to add ransack
  def self.ransackable_attributes(auth_object = nil)
    ["id"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/finance.rb
class Finance < ApplicationRecord
  belongs_to :community
  # Validations
  validates :description, presence: true
  validates :price, presence: true
  validates :period, presence: true
  validates :balance, presence: true

  enum :period, {
    weekly: 0,
    mounthly: 1,
    yearly: 2
  }

  ## update the ransackable below with column you want to add ransack
  def self.ransackable_attributes(auth_object = nil)
    [ "id" ]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/financial.rb
class Financial < ApplicationRecord
  belongs_to :community
  # Validations
  validates :description, presence: true
  validates :price, presence: true
  validates :period, presence: true

  ## update the ransackable below with column you want to add ransack
  def self.ransackable_attributes(auth_object = nil)
    ["id"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  # Validations
  validates :amount, presence: true
  validates :payment_method, presence: true
  validates :notes, presence: true
  validates :status, presence: true
  validates :paid_at, presence: true

  ## update the ransackable below with column you want to add ransack
  def self.ransackable_attributes(auth_object = nil)
    ["id"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/role.rb
class Role < ApplicationRecord
  # Validations
  validates :name, presence: true

  ## update the ransackable below with column you want to add ransack
  def self.ransackable_attributes(auth_object = nil)
    ["id"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # belongs_to :role
  # delegate :name, to: :role, prefix: true

  enum :role, [ :admin, :member ]

  has_many :sessions, dependent: :destroy
  has_many :community_members, dependent: :destroy
  has_many :community, through: :community_members, source: :community
  normalizes :email_address, with: ->(e) { e.strip.downcase }

  before_create :set_default_role

  def set_default_role
    self.role ||= Role.find_by(name: "Member")
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "email_address", "username" ]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_footer.html.erb
<footer class="p-4 my-6 mx-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 xl:p-8 dark:bg-gray-800">
    <ul class="flex flex-wrap items-center mb-6 space-y-1 md:mb-0">
        <li>
            <a href="#" class="mr-4 text-sm font-normal text-gray-500 hover:underline md:mr-6 dark:text-gray-400">Terms and conditions</a>
        </li>
        <li>
            <a href="#" class="mr-4 text-sm font-normal text-gray-500 hover:underline md:mr-6 dark:text-gray-400">Privacy Policy</a>
        </li>
        <li>
            <a href="#" class="mr-4 text-sm font-normal text-gray-500 hover:underline md:mr-6 dark:text-gray-400">Licensing</a>
        </li>
        <li>
            <a href="#" class="mr-4 text-sm font-normal text-gray-500 hover:underline md:mr-6 dark:text-gray-400">Cookie Policy</a>
        </li>
        <li>
            <a href="#" class="text-sm font-normal text-gray-500 hover:underline dark:text-gray-400">Contact</a>
        </li>
    </ul>
    <div class="flex space-x-6 sm:justify-center">
        <a href="#" class="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd"></path>
            </svg>
        </a>
        <a href="#" class="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd"></path>
            </svg>
        </a>
        <a href="#" class="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"></path>
            </svg>
        </a>
        <a href="#" class="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd"></path>
            </svg>
        </a>
        <a href="#" class="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path fill-rule="evenodd" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z" clip-rule="evenodd"></path>
            </svg>
        </a>
    </div>
</footer>

<p class="my-10 text-sm text-center text-gray-500">
    © 2019 - 2023 —
    <a href="/" class="hover:underline" target="_blank">railsapp.com</a>. All rights reserved.
</p>

app/views/shared/_pagination.html.erb
<nav-pagination class="block sticky bottom-0 right-0 items-center w-full p-4 bg-white border-t border-gray-200 sm:flex sm:justify-between dark:bg-gray-800 dark:border-gray-700 pagy">
    <div class="flex items-center mb-4 sm:mb-0 text-gray-400 gap-4">
        <div class="h-10 flex items-center gap-4">
            <%== pagy_prev_a(pagy) %>
            <%== pagy_next_a(pagy) %>
            <%== pagy_info(pagy) %>
        </div>
    </div>
    <div class="flex items-center space-x-3">
        <%= link_to "< Previous", pagy.prev ? url_for(page: pagy.prev) : "#", class: "font-bold px-4 py-2 bg-gray-200 text-gray-600 rounded-md shadow-md hover:bg-gray-300 dark:bg-blue-700 dark:text-gray-300", disabled: !pagy.prev %>
        <%= link_to "Next >", pagy.next ? url_for(page: pagy.next) : "#", class: "font-bold px-4 py-2 bg-gray-200 text-gray-600 rounded-md shadow-md hover:bg-gray-300 dark:bg-blue-700 dark:text-gray-300", disabled: !pagy.next %>
    </div>
</nav-pagination>

app/views/shared/sidebar_menu/_member.html.erb
<li>
  <%= form_tag set_community_session_communities_path, method: :get, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white group", remote: true do %>
    <%= select_tag :community_id, options_from_collection_for_select(Community.all, :id, :name), prompt: "Select a community", class: "block w-full px-3 py-2 text-gray-900 bg-gray-50 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white", onchange: "this.form.submit();" %>
  <% end %>
</li>
<% if @current_community.present? %>
  <li>
    <button type="button" class="flex items-center w-full p-2 text-base text-gray-900 transition duration-75 rounded-lg group hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-700" aria-controls="dropdown-menu-1" data-collapse-toggle="dropdown-menu-1" aria-expanded="false">
      <svg class="w-5 h-5 text-gray-500 transition duration-75 dark:text-white group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M14 6a4 4 0 0 1-4.899-3.899l-1.55.7A4 4 0 1 1 2.122 5.33l-.511 1.372A4 4 0 1 1 3.555 14.6l1.337 1.337A4 4 0 1 1 14 16.657V14.5a2.5 2.5 0 0 1 5 0V18a1 1 0 0 1-1 1h-1a10 10 0 1 1 0-20 10 10 0 0 1 1 19.95V18a1 1 0 0 0-1-1v-1.5a3.5 3.5 0 0 0-7 0v1.5a1 1 0 0 0 1 1v2a1 1 0 0 1-1 1h-6.95A10 10 0 0 1 14 6Z"/>
      </svg>
      <span class="flex-1 ml-3 text-left whitespace-nowrap" sidebar-toggle-item="">My community</span>
      <svg sidebar-toggle-item="" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
      </svg>
    </button>
    <ul id="dropdown-menu-1" class="py-2 space-y-2 hidden">
      <li>
        <%= link_to @current_community, class: "flex items-center p-2 text-base text-gray-900 transition duration-75 rounded-lg pl-11 group hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-700" do %>
          Community
        <% end %>
      </li>
      <li>
        <a href="/roles" class="flex items-center p-2 text-base text-gray-900 transition duration-75 rounded-lg pl-11 group hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-700">Roles</a>
      </li>
    </ul>
  </li>
<% end %>